export const NEC_MEMBERS = [
  { id: "n9", name: "Harsh Shirke", role: "LEAD", department: "NEC TEAM", image: "harsh_shirke.jpg" },
  { id: "n6", name: "Apurva", role: "CO-LEAD", department: "NEC TEAM", image: "apurva.jpg" },
  { id: "n1", name: "Abhijeet", role: "NEC MEMBER", department: "NEC TEAM", image: "abhijeet.jpg" },
  { id: "n2", name: "Aditi Rajput", role: "NEC MEMBER", department: "NEC TEAM", image: "aditi_rajput.jpg" },
  { id: "n3", name: "Aditi Yadav", role: "NEC MEMBER", department: "NEC TEAM", image: "aditi_yadav.png" },
  { id: "n4", name: "Aditya", role: "NEC MEMBER", department: "NEC TEAM", image: "aditya.jpg" },
  { id: "n5", name: "Anvay", role: "NEC MEMBER", department: "NEC TEAM", image: "anvay.jpg" },
  { id: "n7", name: "Atharva Patil", role: "NEC MEMBER", department: "NEC TEAM", image: "atharva_patil.jpg" },
  { id: "n8", name: "Harsh", role: "NEC MEMBER", department: "NEC TEAM", image: "harsh.jpg" },
  { id: "n10", name: "Niki", role: "NEC MEMBER", department: "NEC TEAM", image: "niki.jpg" },
  { id: "n11", name: "Om", role: "NEC MEMBER", department: "NEC TEAM", image: "om.jpg" },
  { id: "n12", name: "Payal", role: "NEC MEMBER", department: "NEC TEAM", image: "payal.jpg" },
  { id: "n13", name: "Poorva", role: "NEC MEMBER", department: "NEC TEAM", image: "poorva.jpg" },
  { id: "n14", name: "Ridhima", role: "NEC MEMBER", department: "NEC TEAM", image: "ridhima.jpg" },
  { id: "n15", name: "Rushikesh", role: "IIT BOMBAY CAMPUS AMBASSADOR", department: "NEC TEAM", image: "rushikesh.jpg" },
  { id: "n16", name: "Sanskruti", role: "NEC MEMBER", department: "NEC TEAM", image: "sanskruti.jpg" },
  { id: "n17", name: "Shreya", role: "NEC MEMBER", department: "NEC TEAM", image: "shreya.jpg" },
  { id: "n18", name: "Swaraj", role: "NEC MEMBER", department: "NEC TEAM", image: "swaraj.jpg" },
  { id: "n19", name: "Tanisha", role: "NEC MEMBER", department: "NEC TEAM", image: "tanisha.jpg" },
  { id: "n20", name: "Utkarsh", role: "NEC MEMBER", department: "NEC TEAM", image: "utkarsh.jpg" },
  { id: "n21", name: "Vishu", role: "NEC MEMBER", department: "NEC TEAM", image: "vishu.png" },
];
